id: I2F4669FD
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T03:56:25.476427'
last_modified: '2022-06-19T03:56:25.476441'
parser: null
source_metadata:
  title: Hagiography of Gos lo gZhon nu dpal (1392–1481)
  author: ཞྭ་དམར་ཆོས་གྲགས་ཡེ་ཤེས།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2012-09-24);
    OCR-proofread; revision in process, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Rime Centre Moscow, OCR-processed
  - Editorial process:ཀུན་དགའ་རྡོ་རྗེ། (kun), Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:མི་རིགས་དཔེ་སྐྲུན་ཁང་། (ed), ཀུན་དགའ་རྡོ་རྗེ། (kun)
  text_witnesses: https://sakyaresearch.org/sources/143
  bases:
    fa21:
      title: Hagiography of Gos lo gZhon nu dpal (1392–1481)
      order: 1
      base_file: fa21.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
